<a href="https://colab.research.google.com/github/peetpeet19/project_dstoolbox/blob/main/satisfaction_SU.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import pandasql

In [ ]:
#!pip install pandas

In [ ]:
#!pip install pandasql

# **Data Clearnsing, Data Tranform**

In [ ]:
results=pd.read_csv("satisfaction_SU.csv") #นำข้อมูลเข้า

In [ ]:
result_df= pd.DataFrame(results)
result_df.shape #ตรวจสอบแถวและคอลัมน์

(122, 10)

In [ ]:
result_df.columns #คอลัมน์มีชื่ออ่ะไรบ้าง

Index(['ประทับเวลา', 'เพศ', 'สถานภาพ', 'คณะ/ หน่วยงาน ',
       'การจัดการเรียนการสอนแบบออนไลน์', 'การช่วยเหลือในส่วนของการลดค่าเทอม',
       'การตอบคำถามที่นักศึกษาสงสัย ผ่านทางช่องทางออนไลน์ {เช่น กยศ/กรอ}',
       'การให้บริการสะดวกรวดเร็ว ครบถ้วน ถูกต้อง ในรูปแบบออนไลน์',
       'การประชาสัมพันธ์ เกี่ยวกับกระบวนการ/ขั้นตอน { การลดค่าเทอม หรือกิจกรรม เป็นต้น } มีขั้นตอนและระยะเวลาในการให้บริการชัดเจน',
       'นักศึกษาอยากได้รับการช่วยเหลือสวัสดิการต่างๆ ในการสนับสนุนการเรียนออนไลน์อะไรบ้าง เช่น ซิมการ์ด , ทุนการศึกษา , อุปกรณ์คอมพิวเตอร์'],
      dtype='object')

In [ ]:
result_df.info() #ตรวจสอบว่าในแต่ล่ะ คอลัมน์ มีกี่แถว และ เป็นข้อมูลอ่ะไร

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 122 entries, 0 to 121
Data columns (total 10 columns):
 #   Column                                                                                                                              Non-Null Count  Dtype
---  ------                                                                                                                              --------------  -----
 0   ประทับเวลา                                                                                                                          122 non-null    object
 1   เพศ                                                                                                                                 122 non-null    object
 2   สถานภาพ                                                                                                                             122 non-null    object
 3   คณะ/ หน่วยงาน                                                                                                                       122 non-null    object
 4   การจัดการเรียนการสอนแบบออนไลน์                                                                                                      122 non-null    int64
 5   การช่วยเหลือในส่วนของการลดค่าเทอม                                                                                                   122 non-null    int64
 6   การตอบคำถามที่นักศึกษาสงสัย ผ่านทางช่องทางออนไลน์ {เช่น กยศ/กรอ}                                                                    122 non-null    int64
 7   การให้บริการสะดวกรวดเร็ว ครบถ้วน ถูกต้อง ในรูปแบบออนไลน์                                                                            122 non-null    int64
 8   การประชาสัมพันธ์ เกี่ยวกับกระบวนการ/ขั้นตอน { การลดค่าเทอม หรือกิจกรรม เป็นต้น } มีขั้นตอนและระยะเวลาในการให้บริการชัดเจน           122 non-null    int64
 9   นักศึกษาอยากได้รับการช่วยเหลือสวัสดิการต่างๆ ในการสนับสนุนการเรียนออนไลน์อะไรบ้าง เช่น ซิมการ์ด , ทุนการศึกษา , อุปกรณ์คอมพิวเตอร์  67 non-null     object
dtypes: int64(5), object(5)
memory usage: 9.7+ KB

In [ ]:
result_df.head()  #ลองแสดงผล ชุด data

            ประทับเวลา  ... นักศึกษาอยากได้รับการช่วยเหลือสวัสดิการต่างๆ ในการสนับสนุนการเรียนออนไลน์อะไรบ้าง เช่น ซิมการ์ด , ทุนการศึกษา , อุปกรณ์คอมพิวเตอร์
0  10/8/2021, 18:02:02  ...                                                NaN
1  10/8/2021, 18:12:09  ...                          ค่าอุปกรณ์การเรียนออนไลน์
2  10/8/2021, 18:13:08  ...                                                NaN
3  10/8/2021, 18:13:21  ...                                                NaN
4  10/8/2021, 18:13:34  ...                                                NaN

[5 rows x 10 columns]

In [ ]:
result_df.isnull().sum() #ตรวจสอบข้อมูล ที่เป็น null

ประทับเวลา                                                                                                                             0
เพศ                                                                                                                                    0
สถานภาพ                                                                                                                                0
คณะ/ หน่วยงาน                                                                                                                          0
การจัดการเรียนการสอนแบบออนไลน์                                                                                                         0
การช่วยเหลือในส่วนของการลดค่าเทอม                                                                                                      0
การตอบคำถามที่นักศึกษาสงสัย ผ่านทางช่องทางออนไลน์ {เช่น กยศ/กรอ}                                                                       0
การให้บริการสะดวกรวดเร็ว ครบถ้วน ถูกต้อง ในรูปแบบออนไลน์                                                                               0
การประชาสัมพันธ์ เกี่ยวกับกระบวนการ/ขั้นตอน { การลดค่าเทอม หรือกิจกรรม เป็นต้น } มีขั้นตอนและระยะเวลาในการให้บริการชัดเจน              0
นักศึกษาอยากได้รับการช่วยเหลือสวัสดิการต่างๆ ในการสนับสนุนการเรียนออนไลน์อะไรบ้าง เช่น ซิมการ์ด , ทุนการศึกษา , อุปกรณ์คอมพิวเตอร์    55
dtype: int64

In [ ]:
result_df.rename(columns={'คณะ/ หน่วยงาน ':'คณะ'},inplace=True)
result_df.rename(columns={'การตอบคำถามที่นักศึกษาสงสัย ผ่านทางช่องทางออนไลน์ {เช่น กยศ/กรอ}':'การตอบคำถามที่นักศึกษาสงสัยออนไลน์'},inplace=True)
result_df.rename(columns={'การให้บริการสะดวกรวดเร็ว ครบถ้วน ถูกต้อง ในรูปแบบออนไลน์':'การให้บริการทางออนไลน์ดี'},inplace=True)
result_df.rename(columns={'การประชาสัมพันธ์ เกี่ยวกับกระบวนการ/ขั้นตอน { การลดค่าเทอม หรือกิจกรรม เป็นต้น } มีขั้นตอนและระยะเวลาในการให้บริการชัดเจน':'การประชาสัมพันธ์ดี'},inplace=True)
result_df.rename(columns={'นักศึกษาอยากได้รับการช่วยเหลือสวัสดิการต่างๆ ในการสนับสนุนการเรียนออนไลน์อะไรบ้าง เช่น ซิมการ์ด , ทุนการศึกษา , อุปกรณ์คอมพิวเตอร์':'นักศึกษาอยากได้รับความช่วยเหลือด้านใด'},inplace=True)
#แปลงชื่อ คอลัมน์ เป็นชื่อสั้นๆเข้าใจง่าย

In [ ]:
result_df.head() #ลองแสดงผล ชุด data

            ประทับเวลา  ... นักศึกษาอยากได้รับความช่วยเหลือด้านใด
0  10/8/2021, 18:02:02  ...                                   NaN
1  10/8/2021, 18:12:09  ...             ค่าอุปกรณ์การเรียนออนไลน์
2  10/8/2021, 18:13:08  ...                                   NaN
3  10/8/2021, 18:13:21  ...                                   NaN
4  10/8/2021, 18:13:34  ...                                   NaN

[5 rows x 10 columns]

In [ ]:
result_df['นักศึกษาอยากได้รับความช่วยเหลือด้านใด'].fillna('ไม่มี',inplace=True) #แปลง NaN เป็น ไม่มี

In [ ]:
result_df['นักศึกษาอยากได้รับความช่วยเหลือด้านใด'].unique() #ตรวจสอบคอลัมน์ นักศึกษาอยากได้รับความช่วยเหลือด้านใด ว่ามีอ่ะไรบ้าง

array(['ไม่มี', 'ค่าอุปกรณ์การเรียนออนไลน์',
       'ทุนการศึกษาและอุปกรณ์เพราะคิดว่าบางคนไม่มีความพร้อมในการเรียนออนไลน์ขนาดนั้นเนื่องด้วยขากอุปกรณ์และทุนทรัพย์',
       'อุปกรคอมพิวเตอร์', 'ห้องสมุดมหาลัยออนไลน์', 'ซิมการ์ด',
       'อยากได้ตังใช้ครับ', 'ทุนการศึกษา', 'ทุนการศึกษาค่ะ ',
       'เพิ่ม Internet', '-', 'อินเตอร์เน็ต อุปกรณ์คอมพิวเตอร์',
       'แพ็คเกจอินเทอร์เน็ตฟรี',
       'อุปกรณ์ในการเรียนออนไลน์ ควรมีให้นักศึกษาทุกคนค่ะ เพราะทุกคนไม่ได้พร้อมเหมือนกันหมด',
       'ไม่ต้องการ',
       'อุปกรณ์อิเล็กทรอนิกส์ที่ใช้ในการเรียน เเละทุนการศึกษา', 'Ipad',
       'อุปกรณ์การเรียน', 'วิตามินบำรุงสายตา หรือแก้ปวดตาค่ะ',
       'อุปกคอมพิวเตอร์',
       'ทุนการศึกษาที่มีกระบวนการขั้นตอนที่ไม่ซับซ้อน ',
       'ถ้าสามารถทำได้อยากให้เมื่อลงชื่อเข้าใช้ผ่านSU-Mail สามารถเข้าใช้Applicationเพื่อการศึกษาผ่านออนไลน์ เช่น Zoom, MS Team,GGMeet ฯลฯ ได้โดยไม่ต้องใช้WIFI',
       'ช่วยเหลือด้านการเรียนดีที่สุดคะ555 ตกต่ำมากเรียนไม่ค่อยเข้าใจแต่ก็เข้าใจอ่าววววเออข้ามไป ซิมการ์ดมั้งคะ😸',
       'แพ็คเกตอินเทอร์เน็ต', 'อุปกรณ์คอมพิวเตอร์',
       'ควรมีทุนการศึกษามีเพียงพอต่อจำนวนนักศึกษา รวมถึงการอุดหนุนอุปกรณ์คอมพิวเตอร์หรืออุปกรณ์อื่นที่เหมาะสมกับการเรียนออนไลน์',
       'อยากให้ช่วยเหลือทางการทุนการศึกษา และอุปกรณ์คอมพิมเตอร์ต่างๆให้ทั้งกับทางนักศึกษาและคณะครูอาจารย์',
       'สิ่งที่มหาวิทยาลัยได้เยียวยาต่อนักศึกษา ยังไม่ได้ประสิทธิภาพ อย่างที่งบประมาณจัดสรรไว้ให้',
       'ทุนการศึกษา/อุปกรณ์อิเล็กทรอนิกส์ที่ใช้ในการเรียน',
       'ควรงดเรียน 1 ปีการศึกษาไม่ใช่นักศึกษาทุกคนที่สามารถมีเทคโนโลยีเข้าเรียนได้ ทางมหาลัยคิดว่านักศึกษาทั้งหมดเข้าถึงสัญญาณอินเทอร์เน็ตได้หรือ และไม่สามารถไปนั่งเรียนนอกบ้านได้เนื่องจากสถานการณ์โควิด - 19 ไม่ควรบอกให้นักศึกษาไปร้านอินเทอร์เน็ตค่ะ',
       ' ทุนการศึกษา', 'เงินน', 'ไม่', 'อยากได้ adobe ค่ะ ', 'ไม่ได้นะ',
       'ทุนการศึกษา\u200b', 'เงิน',
       'จัดหาสิ่งจำเป็นต่างๆในการเรียนออนไลน์ให้เเก่คนที่ต้องการหรือทุกคน',
       'เยียวยาด้านค่าใช้จ่ายให้กับนักศึกษา ', 'ลดค่าเทอม',
       'อุปกรณ์การเรียนสำหรับการเรียนออนไลน์',
       'อยากได้ซิมการ์ดเพราะจะได้ใช้เน็ตในการเรียนออนไลน์และทุนการศึกษาเพราะว่าค่าใช้จ่ายในบางส่วนไม่เพียงพอกับสถานการณ์นี้',
       'อยากได้ทุนการศึกษา ทุนช่วยเหลือ เพิ่มเติม'], dtype=object)

In [ ]:
result_df.loc[result_df.นักศึกษาอยากได้รับความช่วยเหลือด้านใด == 'ค่าอุปกรณ์การเรียนออนไลน์', 'นักศึกษาอยากได้รับความช่วยเหลือด้านใด'] = 'ทุนการศึกษา'
result_df.loc[result_df.นักศึกษาอยากได้รับความช่วยเหลือด้านใด == 'อุปกรคอมพิวเตอร์', 'นักศึกษาอยากได้รับความช่วยเหลือด้านใด'] = 'อุปกรณ์การเรียน'
result_df.loc[result_df.นักศึกษาอยากได้รับความช่วยเหลือด้านใด == 'อยากได้ตังใช้ครับ', 'นักศึกษาอยากได้รับความช่วยเหลือด้านใด'] = 'ทุนการศึกษา'
result_df.loc[result_df.นักศึกษาอยากได้รับความช่วยเหลือด้านใด == 'ทุนการศึกษาค่ะ ', 'นักศึกษาอยากได้รับความช่วยเหลือด้านใด'] = 'ทุนการศึกษา'
result_df.loc[result_df.นักศึกษาอยากได้รับความช่วยเหลือด้านใด == 'เพิ่ม Internet', 'นักศึกษาอยากได้รับความช่วยเหลือด้านใด'] = 'แพ็คเกตอินเทอร์เน็ต'
result_df.loc[result_df.นักศึกษาอยากได้รับความช่วยเหลือด้านใด == 'แพ็คเกจอินเทอร์เน็ตฟรี', 'นักศึกษาอยากได้รับความช่วยเหลือด้านใด'] = 'แพ็คเกตอินเทอร์เน็ต'
result_df.loc[result_df.นักศึกษาอยากได้รับความช่วยเหลือด้านใด == 'ไม่ต้องการ', 'นักศึกษาอยากได้รับความช่วยเหลือด้านใด'] = 'ไม่มี'
result_df.loc[result_df.นักศึกษาอยากได้รับความช่วยเหลือด้านใด == 'Ipad', 'นักศึกษาอยากได้รับความช่วยเหลือด้านใด'] = 'อุปกรณ์การเรียน'
result_df.loc[result_df.นักศึกษาอยากได้รับความช่วยเหลือด้านใด == 'วิตามินบำรุงสายตา หรือแก้ปวดตาค่ะ', 'นักศึกษาอยากได้รับความช่วยเหลือด้านใด'] = 'อุปกรณ์การเรียน'
result_df.loc[result_df.นักศึกษาอยากได้รับความช่วยเหลือด้านใด == 'อุปกคอมพิวเตอร์', 'นักศึกษาอยากได้รับความช่วยเหลือด้านใด'] = 'อุปกรณ์การเรียน'
result_df.loc[result_df.นักศึกษาอยากได้รับความช่วยเหลือด้านใด == 'ทุนการศึกษาที่มีกระบวนการขั้นตอนที่ไม่ซับซ้อน ', 'นักศึกษาอยากได้รับความช่วยเหลือด้านใด'] = 'ทุนการศึกษา'
result_df.loc[result_df.นักศึกษาอยากได้รับความช่วยเหลือด้านใด == 'ถ้าสามารถทำได้อยากให้เมื่อลงชื่อเข้าใช้ผ่านSU-Mail สามารถเข้าใช้Applicationเพื่อการศึกษาผ่านออนไลน์ เช่น Zoom, MS Team,GGMeet ฯลฯ ได้โดยไม่ต้องใช้WIFI', 'นักศึกษาอยากได้รับความช่วยเหลือด้านใด'] = 'อุปกรณ์การเรียน'
result_df.loc[result_df.นักศึกษาอยากได้รับความช่วยเหลือด้านใด == 'ช่วยเหลือด้านการเรียนดีที่สุดคะ555 ตกต่ำมากเรียนไม่ค่อยเข้าใจแต่ก็เข้าใจอ่าววววเออข้ามไป ซิมการ์ดมั้งคะ😸', 'นักศึกษาอยากได้รับความช่วยเหลือด้านใด'] = 'ซิมการ์ด'
result_df.loc[result_df.นักศึกษาอยากได้รับความช่วยเหลือด้านใด == ' ทุนการศึกษา', 'นักศึกษาอยากได้รับความช่วยเหลือด้านใด'] = 'ทุนการศึกษา'
result_df.loc[result_df.นักศึกษาอยากได้รับความช่วยเหลือด้านใด == 'เงินน', 'นักศึกษาอยากได้รับความช่วยเหลือด้านใด'] = 'ทุนการศึกษา'
result_df.loc[result_df.นักศึกษาอยากได้รับความช่วยเหลือด้านใด == 'ไม่', 'นักศึกษาอยากได้รับความช่วยเหลือด้านใด'] = 'ไม่มี'
result_df.loc[result_df.นักศึกษาอยากได้รับความช่วยเหลือด้านใด == 'ไม่ได้นะ', 'นักศึกษาอยากได้รับความช่วยเหลือด้านใด'] = 'ไม่มี'
result_df.loc[result_df.นักศึกษาอยากได้รับความช่วยเหลือด้านใด == 'ทุนการศึกษา\u200b', 'นักศึกษาอยากได้รับความช่วยเหลือด้านใด'] = 'ทุนการศึกษา'
result_df.loc[result_df.นักศึกษาอยากได้รับความช่วยเหลือด้านใด == 'เงิน', 'นักศึกษาอยากได้รับความช่วยเหลือด้านใด'] = 'ทุนการศึกษา'
result_df.loc[result_df.นักศึกษาอยากได้รับความช่วยเหลือด้านใด == 'อยากได้ทุนการศึกษา ทุนช่วยเหลือ เพิ่มเติม', 'นักศึกษาอยากได้รับความช่วยเหลือด้านใด'] = 'ทุนการศึกษา'
result_df.loc[result_df.นักศึกษาอยากได้รับความช่วยเหลือด้านใด == '-', 'นักศึกษาอยากได้รับความช่วยเหลือด้านใด'] = 'ไม่มี'
#แก้คอลัมน์ นักศึกษาอยากได้รับความช่วยเหลือด้านใด ตัวที่ซ้ำกัน และแปลกๆ

In [ ]:
result_df.isnull().sum()

ประทับเวลา                               0
เพศ                                      0
สถานภาพ                                  0
คณะ                                      0
การจัดการเรียนการสอนแบบออนไลน์           0
การช่วยเหลือในส่วนของการลดค่าเทอม        0
การตอบคำถามที่นักศึกษาสงสัยออนไลน์       0
การให้บริการทางออนไลน์ดี                 0
การประชาสัมพันธ์ดี                       0
นักศึกษาอยากได้รับความช่วยเหลือด้านใด    0
dtype: int64

In [ ]:
result_df.head()

            ประทับเวลา  ... นักศึกษาอยากได้รับความช่วยเหลือด้านใด
0  10/8/2021, 18:02:02  ...                                 ไม่มี
1  10/8/2021, 18:12:09  ...                           ทุนการศึกษา
2  10/8/2021, 18:13:08  ...                                 ไม่มี
3  10/8/2021, 18:13:21  ...                                 ไม่มี
4  10/8/2021, 18:13:34  ...                                 ไม่มี

[5 rows x 10 columns]

In [ ]:
result_df.to_csv('satisfaction_SU_หลัง.csv')

In [ ]:
psum = result_df.describe()
psum.head(20)

       การจัดการเรียนการสอนแบบออนไลน์  ...  การประชาสัมพันธ์ดี
count                      122.000000  ...          122.000000
mean                         2.901639  ...            2.991803
std                          0.948333  ...            1.124453
min                          1.000000  ...            1.000000
25%                          2.000000  ...            2.000000
50%                          3.000000  ...            3.000000
75%                          3.000000  ...            4.000000
max                          5.000000  ...            5.000000

[8 rows x 5 columns]

In [ ]:
psum.to_csv('satisfaction_SU_คะแนนรวม.csv')

In [ ]:
qmm =  pandasql.sqldf("select นักศึกษาอยากได้รับความช่วยเหลือด้านใด from result_df group by นักศึกษาอยากได้รับความช่วยเหลือด้านใด")

qmm.head(30)

                นักศึกษาอยากได้รับความช่วยเหลือด้านใด
0   ควรงดเรียน 1 ปีการศึกษาไม่ใช่นักศึกษาทุกคนที่ส...
1   ควรมีทุนการศึกษามีเพียงพอต่อจำนวนนักศึกษา รวมถ...
2   จัดหาสิ่งจำเป็นต่างๆในการเรียนออนไลน์ให้เเก่คน...
3                                            ซิมการ์ด
4                                         ทุนการศึกษา
5   ทุนการศึกษา/อุปกรณ์อิเล็กทรอนิกส์ที่ใช้ในการเรียน
6   ทุนการศึกษาและอุปกรณ์เพราะคิดว่าบางคนไม่มีความ...
7                                           ลดค่าเทอม
8   สิ่งที่มหาวิทยาลัยได้เยียวยาต่อนักศึกษา ยังไม่...
9                               ห้องสมุดมหาลัยออนไลน์
10  อยากให้ช่วยเหลือทางการทุนการศึกษา และอุปกรณ์คอ...
11                                 อยากได้ adobe ค่ะ
12  อยากได้ซิมการ์ดเพราะจะได้ใช้เน็ตในการเรียนออนไ...
13                    อินเตอร์เน็ต อุปกรณ์คอมพิวเตอร์
14                                    อุปกรณ์การเรียน
15               อุปกรณ์การเรียนสำหรับการเรียนออนไลน์
16                                 อุปกรณ์คอมพิวเตอร์
17  อุปกรณ์อิเล็กทรอนิกส์ที่ใช้ในการเรียน เเละทุนก...
18  อุปกรณ์ในการเรียนออนไลน์ ควรมีให้นักศึกษาทุกคน...
19               เยียวยาด้านค่าใช้จ่ายให้กับนักศึกษา
20                                แพ็คเกตอินเทอร์เน็ต
21                                              ไม่มี

In [ ]:
qmm.to_csv('satisfaction_SU_คอมเมนท์.csv')

In [ ]:
#จบบบบบบบบบบบบบบบบบบบบบบบบบบบบบบบบ

# ชุดข้อมูล ชาย

In [59]:
sex_data1 = result_df[(result_df['เพศ']== 'ชาย')]
sex_data1.head()

             ประทับเวลา  ... นักศึกษาอยากได้รับความช่วยเหลือด้านใด
0   10/8/2021, 18:02:02  ...                                 ไม่มี
2   10/8/2021, 18:13:08  ...                                 ไม่มี
7   10/8/2021, 18:19:22  ...                                 ไม่มี
9   10/8/2021, 18:19:32  ...                 ห้องสมุดมหาลัยออนไลน์
12  10/8/2021, 18:20:38  ...                                 ไม่มี

[5 rows x 10 columns]

In [60]:
sex_data1.shape

(30, 10)

In [61]:
sex_pee1= sex_data1[['เพศ','การจัดการเรียนการสอนแบบออนไลน์','การช่วยเหลือในส่วนของการลดค่าเทอม','การตอบคำถามที่นักศึกษาสงสัยออนไลน์','การให้บริการทางออนไลน์ดี','การประชาสัมพันธ์ดี']]
sex_pee1.head()

    เพศ  ...  การประชาสัมพันธ์ดี
0   ชาย  ...                   4
2   ชาย  ...                   2
7   ชาย  ...                   4
9   ชาย  ...                   4
12  ชาย  ...                   4

[5 rows x 6 columns]

In [62]:
sex_pee1.describe()

       การจัดการเรียนการสอนแบบออนไลน์  ...  การประชาสัมพันธ์ดี
count                       30.000000  ...           30.000000
mean                         3.066667  ...            3.200000
std                          0.827682  ...            1.126484
min                          1.000000  ...            1.000000
25%                          3.000000  ...            3.000000
50%                          3.000000  ...            3.000000
75%                          3.750000  ...            4.000000
max                          5.000000  ...            5.000000

[8 rows x 5 columns]

In [63]:
sex_pee11 = sex_pee1.mean()
sex_pee11.to_csv('satisfaction_SU_ชาย.csv')

# ชุดข้อมูล หญิง

In [ ]:
sex_data2 = result_df[(result_df['เพศ']== 'หญิง')]
sex_data2.head()

             ประทับเวลา  ... นักศึกษาอยากได้รับความช่วยเหลือด้านใด
1   10/8/2021, 18:12:09  ...                           ทุนการศึกษา
4   10/8/2021, 18:13:34  ...                                 ไม่มี
8   10/8/2021, 18:19:24  ...                       อุปกรณ์การเรียน
10  10/8/2021, 18:20:24  ...                                 ไม่มี
11  10/8/2021, 18:20:34  ...                                 ไม่มี

[5 rows x 10 columns]

In [ ]:
sex_data2.shape

(80, 10)

In [ ]:
sex_pee2 = sex_data2[['เพศ','การจัดการเรียนการสอนแบบออนไลน์','การช่วยเหลือในส่วนของการลดค่าเทอม','การตอบคำถามที่นักศึกษาสงสัยออนไลน์','การให้บริการทางออนไลน์ดี','การประชาสัมพันธ์ดี']]
sex_pee2.head()

     เพศ  ...  การประชาสัมพันธ์ดี
1   หญิง  ...                   2
4   หญิง  ...                   2
8   หญิง  ...                   3
10  หญิง  ...                   2
11  หญิง  ...                   5

[5 rows x 6 columns]

In [ ]:
sex_pee22 = sex_pee2.mean()
sex_pee22.to_csv('satisfaction_SU_หญิง.csv')

# ชุดข้อมูล LGBTQIA+

In [ ]:
sex_data3 = result_df[(result_df['เพศ']== 'LGBTQIA+')]
sex_data3.head()

             ประทับเวลา  ...              นักศึกษาอยากได้รับความช่วยเหลือด้านใด
3   10/8/2021, 18:13:21  ...                                              ไม่มี
5   10/8/2021, 18:14:24  ...  ทุนการศึกษาและอุปกรณ์เพราะคิดว่าบางคนไม่มีความ...
6   10/8/2021, 18:19:15  ...                                              ไม่มี
17  10/8/2021, 18:22:48  ...                                        ทุนการศึกษา
34  10/8/2021, 18:39:35  ...                                    อุปกรณ์การเรียน

[5 rows x 10 columns]

In [ ]:
sex_data3.shape

(12, 10)

In [ ]:
sex_pee3 = sex_data3[['เพศ','การจัดการเรียนการสอนแบบออนไลน์','การช่วยเหลือในส่วนของการลดค่าเทอม','การตอบคำถามที่นักศึกษาสงสัยออนไลน์','การให้บริการทางออนไลน์ดี','การประชาสัมพันธ์ดี']]
sex_pee3.head()

         เพศ  ...  การประชาสัมพันธ์ดี
3   LGBTQIA+  ...                   1
5   LGBTQIA+  ...                   1
6   LGBTQIA+  ...                   4
17  LGBTQIA+  ...                   1
34  LGBTQIA+  ...                   1

[5 rows x 6 columns]

In [ ]:
sex_pee33= sex_pee3.mean()
sex_pee33.to_csv('satisfaction_SU_LGBTQIA+.csv')

In [ ]:
#จบ 222222222222222222222

# ปี 1

In [ ]:
year_data1 = result_df[(result_df['สถานภาพ']== 'นักศึกษาปริญญาตรีชั้นปีที่ 1')]
year_data1.head()

             ประทับเวลา  ... นักศึกษาอยากได้รับความช่วยเหลือด้านใด
6   10/8/2021, 18:19:15  ...                                 ไม่มี
7   10/8/2021, 18:19:22  ...                                 ไม่มี
8   10/8/2021, 18:19:24  ...                       อุปกรณ์การเรียน
9   10/8/2021, 18:19:32  ...                 ห้องสมุดมหาลัยออนไลน์
13  10/8/2021, 18:21:37  ...                              ซิมการ์ด

[5 rows x 10 columns]

In [ ]:
year_data1.shape

(35, 10)

In [ ]:
year_pee1 = year_data1[['สถานภาพ','การจัดการเรียนการสอนแบบออนไลน์','การช่วยเหลือในส่วนของการลดค่าเทอม','การตอบคำถามที่นักศึกษาสงสัยออนไลน์','การให้บริการทางออนไลน์ดี','การประชาสัมพันธ์ดี']]
year_pee1.describe()

       การจัดการเรียนการสอนแบบออนไลน์  ...  การประชาสัมพันธ์ดี
count                       35.000000  ...            35.00000
mean                         3.057143  ...             3.40000
std                          1.136115  ...             1.31059
min                          1.000000  ...             1.00000
25%                          2.500000  ...             3.00000
50%                          3.000000  ...             4.00000
75%                          4.000000  ...             4.00000
max                          5.000000  ...             5.00000

[8 rows x 5 columns]

In [ ]:
year_pee11= year_pee1.mean()
year_pee11.to_csv('satisfaction_SU_นักศึกษาปริญญาตรีชั้นปีที่ 1.csv')

# ปี 2

In [ ]:
year_data2 = result_df[(result_df['สถานภาพ']== 'นักศึกษาปริญญาตรีชั้นปีที่ 2')]
year_data2.head()

            ประทับเวลา  ...              นักศึกษาอยากได้รับความช่วยเหลือด้านใด
0  10/8/2021, 18:02:02  ...                                              ไม่มี
2  10/8/2021, 18:13:08  ...                                              ไม่มี
3  10/8/2021, 18:13:21  ...                                              ไม่มี
4  10/8/2021, 18:13:34  ...                                              ไม่มี
5  10/8/2021, 18:14:24  ...  ทุนการศึกษาและอุปกรณ์เพราะคิดว่าบางคนไม่มีความ...

[5 rows x 10 columns]

In [ ]:
year_data2.shape

(64, 10)

In [ ]:
year_pee2 = year_data2[['สถานภาพ','การจัดการเรียนการสอนแบบออนไลน์','การช่วยเหลือในส่วนของการลดค่าเทอม','การตอบคำถามที่นักศึกษาสงสัยออนไลน์','การให้บริการทางออนไลน์ดี','การประชาสัมพันธ์ดี']]
year_pee2.describe()

       การจัดการเรียนการสอนแบบออนไลน์  ...  การประชาสัมพันธ์ดี
count                       64.000000  ...           64.000000
mean                         2.921875  ...            2.781250
std                          0.822398  ...            0.950668
min                          1.000000  ...            1.000000
25%                          3.000000  ...            2.000000
50%                          3.000000  ...            3.000000
75%                          3.000000  ...            3.000000
max                          5.000000  ...            5.000000

[8 rows x 5 columns]

In [ ]:
year_pee22= year_pee2.mean()
year_pee22.to_csv('satisfaction_SU_นักศึกษาปริญญาตรีชั้นปีที่ 2.csv')

# ปี 3

In [ ]:
year_data3 = result_df[(result_df['สถานภาพ']== 'นักศึกษาปริญญาตรีชั้นปีที่ 3')]
year_data3.head()

              ประทับเวลา  ...              นักศึกษาอยากได้รับความช่วยเหลือด้านใด
25   10/8/2021, 18:29:38  ...                                        ทุนการศึกษา
47   10/8/2021, 18:59:10  ...                                    อุปกรณ์การเรียน
71   10/8/2021, 19:23:33  ...  ทุนการศึกษา/อุปกรณ์อิเล็กทรอนิกส์ที่ใช้ในการเรียน
100  10/8/2021, 22:26:51  ...               เยียวยาด้านค่าใช้จ่ายให้กับนักศึกษา
105  10/8/2021, 23:07:44  ...                                              ไม่มี

[5 rows x 10 columns]

In [ ]:
year_data3.shape

(9, 10)

In [ ]:
year_pee3 = year_data3[['สถานภาพ','การจัดการเรียนการสอนแบบออนไลน์','การช่วยเหลือในส่วนของการลดค่าเทอม','การตอบคำถามที่นักศึกษาสงสัยออนไลน์','การให้บริการทางออนไลน์ดี','การประชาสัมพันธ์ดี']]
year_pee3.describe()

       การจัดการเรียนการสอนแบบออนไลน์  ...  การประชาสัมพันธ์ดี
count                        9.000000  ...            9.000000
mean                         2.555556  ...            3.222222
std                          1.130388  ...            1.301708
min                          1.000000  ...            1.000000
25%                          2.000000  ...            2.000000
50%                          3.000000  ...            4.000000
75%                          3.000000  ...            4.000000
max                          4.000000  ...            5.000000

[8 rows x 5 columns]

In [ ]:
year_pee33= year_pee3.mean()
year_pee33.to_csv('satisfaction_SU_นักศึกษาปริญญาตรีชั้นปีที่ 3.csv')

# ปี 4

In [ ]:
year_data4 = result_df[(result_df['สถานภาพ']== 'นักศึกษาปริญญาตรีชั้นปีที่ 4')]
year_data4.head()

             ประทับเวลา  ... นักศึกษาอยากได้รับความช่วยเหลือด้านใด
1   10/8/2021, 18:12:09  ...                           ทุนการศึกษา
10  10/8/2021, 18:20:24  ...                                 ไม่มี
12  10/8/2021, 18:20:38  ...                                 ไม่มี
17  10/8/2021, 18:22:48  ...                           ทุนการศึกษา
19  10/8/2021, 18:23:37  ...                   แพ็คเกตอินเทอร์เน็ต

[5 rows x 10 columns]

In [ ]:
year_data4.shape

(14, 10)

In [ ]:
year_pee4 = year_data4[['สถานภาพ','การจัดการเรียนการสอนแบบออนไลน์','การช่วยเหลือในส่วนของการลดค่าเทอม','การตอบคำถามที่นักศึกษาสงสัยออนไลน์','การให้บริการทางออนไลน์ดี','การประชาสัมพันธ์ดี']]
year_pee4.describe()

       การจัดการเรียนการสอนแบบออนไลน์  ...  การประชาสัมพันธ์ดี
count                       14.000000  ...           14.000000
mean                         2.642857  ...            2.785714
std                          0.841897  ...            1.050902
min                          1.000000  ...            1.000000
25%                          2.250000  ...            2.000000
50%                          3.000000  ...            3.000000
75%                          3.000000  ...            3.750000
max                          4.000000  ...            4.000000

[8 rows x 5 columns]

In [ ]:
year_pee44= year_pee4.mean()
year_pee44.to_csv('satisfaction_SU_นักศึกษาปริญญาตรีชั้นปีที่ 4.csv')

In [ ]:
#จบ 333333333333333333